#---------------------------------#
#    environment configuration    #
#---------------------------------#

# build worker image (VM template)
image: Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: ./build/build.ps1
